# Reference: https://github.com/i3/i3/blob/next/etc/config

config-version = 2

# In i3, all workspaces are phantom
persistent-workspaces = []

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    option-enter = '''exec-and-forget osascript -e '
    tell application "Terminal"
        do script
        activate
    end tell'
    '''

    # i3 wraps focus by default
    option-j =         'focus --boundaries-action wrap-around-the-workspace left'
    option-k =         'focus --boundaries-action wrap-around-the-workspace down'
    option-l =         'focus --boundaries-action wrap-around-the-workspace up'
    option-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

    option-shift-j = 'move left'
    option-shift-k = 'move down'
    option-shift-l = 'move up'
    option-shift-semicolon = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    option-h = 'split horizontal'
    option-v = 'split vertical'

    option-f = 'fullscreen'

    option-s = 'layout v_accordion' # 'layout stacking' in i3
    option-w = 'layout h_accordion' # 'layout tabbed' in i3
    option-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    option-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in Airlock mental model.
    #option-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all
    # option-a = 'focus parent'

    option-1 = 'workspace 1'
    option-2 = 'workspace 2'
    option-3 = 'workspace 3'
    option-4 = 'workspace 4'
    option-5 = 'workspace 5'
    option-6 = 'workspace 6'
    option-7 = 'workspace 7'
    option-8 = 'workspace 8'
    option-9 = 'workspace 9'
    option-0 = 'workspace 10'

    option-shift-1 = 'move-node-to-workspace 1'
    option-shift-2 = 'move-node-to-workspace 2'
    option-shift-3 = 'move-node-to-workspace 3'
    option-shift-4 = 'move-node-to-workspace 4'
    option-shift-5 = 'move-node-to-workspace 5'
    option-shift-6 = 'move-node-to-workspace 6'
    option-shift-7 = 'move-node-to-workspace 7'
    option-shift-8 = 'move-node-to-workspace 8'
    option-shift-9 = 'move-node-to-workspace 9'
    option-shift-0 = 'move-node-to-workspace 10'

    option-shift-c = 'reload-config'

    option-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'
