= Airlock Workflow Examples
include::util/site-attributes.adoc[]

include::util/header.adoc[]

These examples use Airlock commands and macOS tools. Adapt app names, paths, and shortcuts to your setup.
Share improvements through https://github.com/jss367/Airlock/issues[issues] or pull requests.

[#move-by-dragging-any-part-of-the-window]
== Move windows by dragging any part of the window

[source,bash]
----
defaults write -g NSWindowShouldDragOnGesture -bool true
----

Now, you can move windows by holding `ctrl + cmd` and dragging any part of the window (not necessarily the window title)

[#non-native-fullscreen-in-firefox]
== Non-native fullscreen in Firefox

Change the following settings in `about:config`:

----
// Disable macOS native fullscreen in Firefox
full-screen-api.macos-native-full-screen = false

// Disable fullscreen transition animations
full-screen-api.transition-duration.enter = 0 0
full-screen-api.transition-duration.leave = 0 0
----

`full-screen-api.ignore-widgets` is also an interesting config knob that might be of your preference.

[#highlight-focused-windows-with-colored-borders]
== Highlight focused windows with colored borders

To highlight the focused window with colored border you can use link:https://github.com/FelixKratz/JankyBorders[JankyBorders].

You can also use `after-startup-command` to start JankyBorders together with Airlock

[source,toml]
----
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on Airlock restart
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]
----

[#disable-open-animations]
== Disable windows opening animations

Observable in Google Chrome

[source,bash]
----
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false
----

[#use-trackpad-gestures-to-switch-workspaces]
== Use trackpad gestures to switch workspaces

The following commands focus next or previous workspaces on monitors where the mouse is located

[source,bash]
----
airlock workspace "$(airlock list-workspaces --monitor mouse --visible)" && airlock workspace next

airlock workspace "$(airlock list-workspaces --monitor mouse --visible)" && airlock workspace prev
----

Assign these commands in a gesture tool that can run shell commands. Use the full path to the `airlock` executable if the tool does not inherit your terminal's `PATH`.

[#open-a-new-window-with-applescript]
== Open a new window with AppleScript

Use xref:commands.adoc#summon-app[summon-app] to bring an app to the current workspace. When you specifically need a new Safari or Terminal window, you can use AppleScript:

Opening *a new window* of a program that can support multiple windows (such as Safari or Terminal.app) can be accomplished with an AppleScript inlined in `airlock.toml` as follows:

- Safari
+
[source,toml]
----
ctrl-g = '''exec-and-forget osascript -e '
tell application "Safari"
    make new document at end of documents
    activate
end tell'
'''
----
- Terminal
+
[source,toml]
----
ctrl-g = '''exec-and-forget osascript -e '
tell application "Terminal"
    do script
    activate
end tell'
'''
----

[#disable-hide-app]
== Disable the hide-application shortcut

If `automatically-unhide-macos-hidden-apps` isn't enough, you can disable `cmd-h` altogether (which will make this hotkey unavailable for apps that might use it for other purposes)

.~/.airlock.toml
[source,toml]
----
[mode.main.binding]
    cmd-h = [] # Disable "hide application"
    cmd-option-h = [] # Disable "hide others"
----

[#screenshoot-shortcut]
== Take screenshots to clipboard using keyboard shortcut

You can configure a custom shortcut to take a screenshot.
`screencapture` is a built-in macOS command.

.~/.airlock.toml
[source,toml]
----
option-shift-s = 'exec-and-forget screencapture -i -c'
----

[#i3-like-config]
== i3 like config

link:config-examples/i3-like-config-example.toml[Download i3-like-config.toml]

[source,toml,subs="macros+,specialchars+"]
----
include::config-examples/i3-like-config-example.toml[]
----

[#popular-apps-ids]
== List of Apple application IDs

The list is useful to compose custom xref:guide.adoc#on-window-detected-callback[on-window-detected callback].

[cols="1,3"]
|===
|Application name|Application ID

|Activity Monitor|`com.apple.ActivityMonitor`
|AirPort Utility|`com.apple.airport.airportutility`
|App Store|`com.apple.AppStore`
|Audio MIDI Setup|`com.apple.audio.AudioMIDISetup`
|Automator|`com.apple.Automator`
|Books|`com.apple.iBooksX`
|Calculator|`com.apple.calculator`
|Calendar|`com.apple.iCal`
|Chess|`com.apple.Chess`
|Clock|`com.apple.clock`
|ColorSync Utility|`com.apple.ColorSyncUtility`
|Console|`com.apple.Console`
|Contacts|`com.apple.AddressBook`
|Dictionary|`com.apple.Dictionary`
|Disk Utility|`com.apple.DiskUtility`
|FaceTime|`com.apple.FaceTime`
|Find My|`com.apple.findmy`
|Finder|`com.apple.finder`
|Freeform|`com.apple.freeform`
|Grapher|`com.apple.grapher`
|Home|`com.apple.Home`
|iMovie|`com.apple.iMovieApp`
|Keychain Access|`com.apple.keychainaccess`
|Keynote|`com.apple.iWork.Keynote`
|Mail|`com.apple.mail`
|Maps|`com.apple.Maps`
|Messages|`com.apple.MobileSMS`
|Music|`com.apple.Music`
|Notes|`com.apple.Notes`
|Pages|`com.apple.iWork.Pages`
|Photo Booth|`com.apple.PhotoBooth`
|Photos|`com.apple.Photos`
|Podcasts|`com.apple.podcasts`
|Preview|`com.apple.Preview`
|QuickTime Player|`com.apple.QuickTimePlayerX`
|Reminders|`com.apple.reminders`
|Safari|`com.apple.Safari`
|Shortcuts|`com.apple.shortcuts`
|Stocks|`com.apple.stocks`
|System Settings|`com.apple.systempreferences`
|Terminal|`com.apple.Terminal`
|TextEdit|`com.apple.TextEdit`
|Time Machine|`com.apple.backup.launcher`
|TV|`com.apple.TV`
|VoiceMemos|`com.apple.VoiceMemos`
|VoiceOver Utility|`com.apple.VoiceOverUtility`
|Weather|`com.apple.weather`
|Xcode|`com.apple.dt.Xcode`

|===
